#!/usr/bin/env python3
"""Generates src/core/champion_names.c from Jonathan's names spreadsheet.

Usage: tools/assets/gen_champion_names.py ["/path/to/Champion Names in 3 languages.xlsx"]

The sheet is grouped by colour section ("INDIGO Champions"...) then species
block ("Order B - Centaure (Centaur)"), each block a header row followed by
French/English/Spanish rows. Names are matched to champion_id by taking each
(colour, species) group's names in sheet order against that group's cards in
ascending champion_id order in fullDeck (src/core/game_constants.c) -- verified
2026-09-28 against the printed cards (Furial/Furie/Lof = ids 1/35/69 ...).
Fails loudly on any count mismatch rather than guessing.
"""
import re, sys, openpyxl

XLSX = sys.argv[1] if len(sys.argv) > 1 else \
    "/mnt/nougatoctet/oracle/Champion Names in 3 languages.xlsx"
COLOURS = {"ORANGE": "ORANGE", "ROUGE": "RED", "INDIGO": "INDIGO"}

# --- sheet: {(colour, SPECIES): [(fr, en, es), ...]} ---
groups, colour, species = {}, None, None
for row in openpyxl.load_workbook(XLSX, data_only=True).active.iter_rows(values_only=True):
    a, b, c = (row + (None, None, None))[:3]
    if a and not b and not c:
        m = re.match(r"(\w+) Champions", a)
        if m:
            colour = COLOURS[m.group(1)]
            continue
        m = re.match(r"Order \w - .*\((\w+)\)", a)
        if m:
            species = m.group(1).upper()
            groups[(colour, species)] = []
            continue
    if a and b and c and a != "French":
        groups[(colour, species)].append((a.strip(), b.strip(), c.strip()))

# --- deck: {(colour, SPECIES): [champion_id, ...]} ---
src = open(__file__.rsplit("/tools/", 1)[0] + "/src/core/game_constants.c").read()
deck = {}
for id_, col, spc in re.findall(
        r"\{CHAMPION_CARD, \d+, (\d+), \d+, \d+, COLOR_(\w+), SPECIES_(\w+),", src):
    deck.setdefault((col, spc), []).append(int(id_))

assert set(groups) == set(deck), (set(groups) ^ set(deck))
names = {}
for key, ids in deck.items():
    assert len(groups[key]) == len(ids) == len(set(ids)), (key, len(groups[key]), len(ids))
    for id_, n in zip(sorted(ids), groups[key]):
        names[id_] = n
assert sorted(names) == list(range(1, 103)), "expected champion_id 1-102"

def c(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

out = ["// champion_names.c -- GENERATED by tools/assets/gen_champion_names.py from",
       "// \"Champion Names in 3 languages.xlsx\" (Jonathan's source of truth); do not",
       "// hand-edit -- regenerate. See champion_names.h.", "",
       '#include "champion_names.h"', "",
       "// Indexed [champion_id - 1][ui_language_t]: English, French, Spanish.",
       "static const char* const CHAMPION_NAMES[CHAMPION_COUNT][3] =", "{"]
for i in range(1, 103):
    fr, en, es = names[i]
    out.append(f"  {{ {c(en)}, {c(fr)}, {c(es)} }}, // {i}")
out += ["};", "",
        "const char* champion_name(uint8_t champion_id, ui_language_t lang)",
        "{ if(champion_id < 1 || champion_id > CHAMPION_COUNT || (unsigned)lang > LANG_ES)",
        "    return \"\";",
        "  return CHAMPION_NAMES[champion_id - 1][lang];",
        "} // champion_name", ""]
open(__file__.rsplit("/tools/", 1)[0] + "/src/core/champion_names.c", "w").write("\n".join(out))
print("wrote src/core/champion_names.c: 102 champions")
