// champion_names.c -- GENERATED by tools/assets/gen_champion_names.py from
// "Champion Names in 3 languages.xlsx" (Jonathan's source of truth); do not
// hand-edit -- regenerate. See champion_names.h.

#include "champion_names.h"

// Indexed [champion_id - 1][ui_language_t]: English, French, Spanish.
static const char* const CHAMPION_NAMES[CHAMPION_COUNT][3] =
{
  { "Furial", "Furial", "Furial" }, // 1
  { "Mimosa Cotton", "Mimosa Cotton", "Mimosa Algodón" }, // 2
  { "Demata", "Démata", "Démata" }, // 3
  { "Artemis", "Artémis", "Artemisa" }, // 4
  { "Tremoma Sierra", "Tremoma Sièra", "Tremoma Sierra" }, // 5
  { "Sourlio", "Sourlio", "Surlío" }, // 6
  { "Tolman", "Tolman", "Tolman" }, // 7
  { "Roze", "Roze", "Roze" }, // 8
  { "Larg", "Larg", "Larg" }, // 9
  { "Zaltar", "Zaltar", "Zaltar" }, // 10
  { "Zephyr", "Zephyr", "Céfiro" }, // 11
  { "Isum", "Isum", "Isum" }, // 12
  { "Sajeff", "Sajeff", "Sajeff" }, // 13
  { "Ta", "Ta", "Ta" }, // 14
  { "Ignis", "Ignis", "Ignis" }, // 15
  { "Voice of Wind", "Voix du vent", "Voz del Viento" }, // 16
  { "Nivalise", "Nivalise", "Nivalís" }, // 17
  { "Neg", "Neg", "Neg" }, // 18
  { "Lily Flower", "Fleur de Lys", "Flor de Lis" }, // 19
  { "Galaxim", "Galaxim", "Galaxim" }, // 20
  { "Galak", "Galak", "Galak" }, // 21
  { "Onyx", "Onyx", "Ónice" }, // 22
  { "Zaan", "Zaan", "Zaan" }, // 23
  { "Harvent", "Harvent", "Harvent" }, // 24
  { "Ekaye", "Ékaye", "Ékaye" }, // 25
  { "Goog", "Goog", "Gug" }, // 26
  { "Meriadoc", "Meriadoc", "Meriadoc" }, // 27
  { "Ceolsara", "Ceolsara", "Ceolsara" }, // 28
  { "Opal", "Opale", "Ópalo" }, // 29
  { "Tross", "Tross", "Tros" }, // 30
  { "Zarg", "Zarg", "Zarg" }, // 31
  { "Merwig", "Merwig", "Merwig" }, // 32
  { "Kimjo", "Kimjo", "Kimjo" }, // 33
  { "Aero", "Aero", "Aero" }, // 34
  { "Fury", "Furie", "Furia" }, // 35
  { "Horned", "Cornu", "Cornudo" }, // 36
  { "Gropeti", "Gropeti", "Gropeti" }, // 37
  { "Fantur", "Fantur", "Fantur" }, // 38
  { "Thokk", "Thokk", "Thokk" }, // 39
  { "Magicha", "Magicha", "Magicha" }, // 40
  { "Eskwa", "Eskwa", "Eskwa" }, // 41
  { "Cerp", "Cerp", "Cerp" }, // 42
  { "Vraaz", "Vraaz", "Vraaz" }, // 43
  { "Krogg", "Krogg", "Krogg" }, // 44
  { "Whiskers", "Moustache", "Bigotes" }, // 45
  { "Galadriel", "Galadriel", "Galadriel" }, // 46
  { "Eksob", "Eksob", "Eksob" }, // 47
  { "Bobelin", "Bobelin", "Bobelín" }, // 48
  { "Zargoth", "Zargoth", "Zargoth" }, // 49
  { "Shami", "Shami", "Shami" }, // 50
  { "Stone Eye", "Œil de Pierre", "Ojo de Piedra" }, // 51
  { "Lezol", "Lezol", "Lezol" }, // 52
  { "Oakblade", "Lame de Chêne", "Hoja de Roble" }, // 53
  { "Skarn", "Skarn", "Skarn" }, // 54
  { "Rapire", "Rapire", "Rapire" }, // 55
  { "Pan", "Pan", "Pan" }, // 56
  { "Cirdan", "Cirdan", "Cirdan" }, // 57
  { "Carmael", "Carmael", "Carmael" }, // 58
  { "Oc", "Oc", "Oc" }, // 59
  { "Tchak", "Tchak", "Chak" }, // 60
  { "Great Sage", "Grand Sage", "Gran Sabio" }, // 61
  { "Sol'dor", "Sol'dor", "Sol'dor" }, // 62
  { "Typhon", "Typhon", "Tifón" }, // 63
  { "Casitigr", "Casitigr", "Casitigr" }, // 64
  { "Fiza", "Fiza", "Fiza" }, // 65
  { "Clover", "Trèfle", "Trébol" }, // 66
  { "Eglewin", "Eglewin", "Eglewin" }, // 67
  { "Stealthy", "Furtif", "Furtivo" }, // 68
  { "Lof", "Lof", "Lof" }, // 69
  { "Fulgur", "Fulgur", "Fúlgur" }, // 70
  { "Galaxor", "Galaxor", "Galaxor" }, // 71
  { "Lo", "Lo", "Lo" }, // 72
  { "Littlehorn", "Licornette", "Unicornita" }, // 73
  { "Kafur", "Kafur", "Kafur" }, // 74
  { "Ebony Horn", "Corne d'ébène", "Cuerno de Ébano" }, // 75
  { "Mountain Foam", "Écume des montagnes", "Espuma de las Montañas" }, // 76
  { "Grapior", "Grapior", "Grapior" }, // 77
  { "Moon", "Lune", "Luna" }, // 78
  { "Eksel", "Eksel", "Eksel" }, // 79
  { "Flik", "Flik", "Flik" }, // 80
  { "Flak", "Flak", "Flak" }, // 81
  { "Taur", "Taur", "Taur" }, // 82
  { "Undine", "Ondine", "Ondina" }, // 83
  { "Kookie", "Viskui", "Bizqui" }, // 84
  { "Celeste", "Céleste", "Celeste" }, // 85
  { "Castar", "Castar", "Castar" }, // 86
  { "Eurytion", "Eurytion", "Euritión" }, // 87
  { "Titania", "Titania", "Titania" }, // 88
  { "Arpir", "Arpir", "Arpir" }, // 89
  { "Kentaur", "Kentaur", "Kentaur" }, // 90
  { "Flouk", "Flouk", "Fluk" }, // 91
  { "Japal", "Japal", "Japal" }, // 92
  { "Aveline", "Aveline", "Avelina" }, // 93
  { "Loicap", "Loïcap", "Loicap" }, // 94
  { "Lightning", "Éclair", "Relámpago" }, // 95
  { "Nomicro", "Nomicro", "Nomicro" }, // 96
  { "Lyra", "Lyra", "Lyra" }, // 97
  { "Lapir", "Lapir", "Lapir" }, // 98
  { "Kapir", "Kapir", "Kapir" }, // 99
  { "Tempest", "Tempête", "Tempestad" }, // 100
  { "Bombur", "Bombur", "Bombur" }, // 101
  { "Wolfly", "Casilou", "Caslobito" }, // 102
};

const char* champion_name(uint8_t champion_id, ui_language_t lang)
{ if(champion_id < 1 || champion_id > CHAMPION_COUNT || (unsigned)lang > LANG_ES)
    return "";
  return CHAMPION_NAMES[champion_id - 1][lang];
} // champion_name
